packages:
  - "packages/*"
  - "ui/*"
  - "test/*"
  - "site/*"
  - "site/!lib"

catalog:
  '@apollo/client': ^3.14.0
  '@graphql-codegen/add': ^5.0.3
  '@graphql-codegen/cli': ^5.0.3
  '@graphql-codegen/import-types-preset': ^3.0.0
  '@graphql-codegen/near-operation-file-preset': ^3.1.0
  '@graphql-codegen/typed-document-node': ^5.1.2
  '@graphql-codegen/typescript': ^4.1.6
  '@graphql-codegen/typescript-operations': ^4.6.1
  '@graphql-typed-document-node/core': ^3.2.0
  '@babel/plugin-proposal-decorators': ^7.22.5
  '@babel/plugin-proposal-export-default-from': ^7.22.5
  '@babel/plugin-transform-runtime': ^7.22.5
  '@babel/preset-env': ^7.22.5
  '@babel/preset-react': ^7.22.5
  '@babel/preset-typescript': ^7.22.5
  '@babel/runtime': ^7.22.5
  '@babel/core': ^7.22.5
  '@loadable/babel-plugin': ^5.16.1
  '@loadable/component': ^5.16.7
  '@loadable/server': ^5.16.7
  '@loadable/webpack-plugin': ^5.15.2
  '@pmmmwh/react-refresh-webpack-plugin': ^0.6.1
  '@rollup/plugin-alias': ^5.1.1
  '@swc/core': ^1.10.15
  '@types/cookie-parser': ^1.4.9
  '@types/express': ^4.17.23
  '@types/loadable__component': ^5.13.10
  '@types/loadable__server': ^5.12.11
  '@types/lodash': ^4.17.20
  '@types/node': ^22.18.10
  '@types/react': ^18.3.26
  '@types/react-dom': ^18.3.7
  '@types/webpack-env': ^1.18.8
  '@types/webpack-hot-middleware': ^2.25.11
  '@types/webpack-node-externals': ^3.0.4
  '@vitejs/plugin-react': ^5.0.4
  'animate.css': ^4.1.1
  autoprefixer: ^10.4.21
  axios: ^1.12.2
  babel-plugin-react-compiler: 1.0.0
  babel-loader: ^10.0.0
  browserslist: ^4.26.3
  codemirror: ^5.65.18
  cookie-parser: ^1.4.7
  core-js: ^3.46.0
  cors: ^2.8.5
  cross-env: ^10.1.0
  cross-fetch: ^4.1.0
  cross-port-killer: ^1.4.0
  css-loader: ^7.1.2
  css-minimizer-webpack-plugin: ^7.0.2
  dayjs: ^1.11.18
  dotenv: ^16.4.5
  echarts: ^4.9.0
  eslint: ^8.57.0
  eslint-webpack-plugin: ^4.2.0
  express: 4.21.2
  express-session: ^1.18.2
  fast-folder-size: ^2.4.0
  file-loader: ^6.2.0
  fork-ts-checker-webpack-plugin: ^9.1.0
  graphql: ^16.11.0
  husky: ^9.1.5
  immer: ^9.0.21
  jquery: ^3.7.0
  lodash: ^4.17.21
  lodash-es: ^4.17.21
  mime: ^3.0.0
  mini-css-extract-plugin: ^2.9.4
  module-alias: ^2.2.3
  multer: ^1.4.5-lts.1
  pino: ^9.13.1
  pino-pretty: ^13.1.2
  postcss: ^8.5.6
  postcss-loader: ^8.2.0
  prettier: ^3.6.2
  pretty-bytes: ^5
  react: ^18.3.1
  react-compiler-runtime: 1.0.0
  react-dom: ^18.3.1
  react-refresh: ^0.18.0
  react-router: ^6.30.1
  react-router-dom: ^6.30.1
  reactivity-store: ^0.3.11
  redux: ^5.0.1
  redux-saga: ^1.3.0
  redux-thunk: ^3.1.0
  regenerator-runtime: ^0.14.1
  sass: ^1.89.2
  sass-loader: ^16.0.5
  style-loader: ^4.0.0
  tailwindcss: ^3.4.18
  thread-loader: ^4.0.4
  ts-node: ^10.9.2
  tslib: ^2.8.0
  typescript: ^5.3.3
  vite: ^5.4.20
  vite-tsconfig-paths: ^5.1.4
  webpack: ^5.99.5
  webpack-bundle-analyzer: ^4.10.2
  webpack-dev-middleware: ^7.4.5
  webpack-dev-server: ^5.2.2
  webpack-hot-middleware: ^2.26.1
  webpack-manifest-plugin: ^5.0.1
  webpack-merge: ^5.10.0
  webpack-node-externals: ^3.0.0
