/**
 * @file Client Reference Code Generation
 * Generate client reference proxy code for server-side rendering
 */

/**
 * Generate client reference proxy code for server-side rendering
 *
 * @param moduleId - The module ID
 * @param exports - Named exports
 * @param hasDefaultExport - Whether there's a default export
 * @returns Generated proxy code
 */
export function generateClientReferenceProxyCode(moduleId: string, exports: string[], hasDefaultExport: boolean): string {
  const lines: string[] = [
    "// Client reference proxy generated by @my-react/react-vite RSC",
    'const CLIENT_REFERENCE_SYMBOL = Symbol.for("react.client.reference");',
    "",
    "function createClientReference(moduleId, exportName) {",
    "  const ref = {",
    "    $$typeof: CLIENT_REFERENCE_SYMBOL,",
    "    $$id: moduleId,",
    "    $$name: exportName,",
    "  };",
    "  // Make it callable for component usage",
    "  const proxy = new Proxy(function() {}, {",
    "    get(target, prop) {",
    "      if (prop === '$$typeof') return ref.$$typeof;",
    "      if (prop === '$$id') return ref.$$id;",
    "      if (prop === '$$name') return ref.$$name;",
    "      return undefined;",
    "    },",
    "    apply() {",
    "      throw new Error(",
    '        `[@my-react/react-server] Cannot call client component "${exportName}" on the server. ` +',
    '        "Client components can only be rendered on the client."',
    "      );",
    "    },",
    "  });",
    "  Object.assign(proxy, ref);",
    "  return proxy;",
    "}",
    "",
  ];

  // Generate exports
  if (hasDefaultExport) {
    lines.push(`const __default__ = createClientReference(${JSON.stringify(moduleId)}, "default");`);
    lines.push("export default __default__;");
    lines.push("");
  }

  for (const exportName of exports) {
    // Ensure valid JS identifier
    const safeName = exportName.replace(/[^a-zA-Z0-9_$]/g, "_");
    lines.push(`export const ${safeName} = createClientReference(${JSON.stringify(moduleId)}, ${JSON.stringify(exportName)});`);
  }

  return lines.join("\n");
}

/**
 * Create a module proxy for all exports in a module
 * Used when you need to reference an entire client module
 *
 * @param moduleId - The module ID
 * @returns Proxy code for the entire module
 */
export function createClientModuleProxy(moduleId: string): string {
  return `
// Client module proxy generated by @my-react/react-vite RSC
 const CLIENT_REFERENCE_SYMBOL = Symbol.for("react.client.reference");

export function createClientModuleProxy(moduleId) {
  return new Proxy({}, {
    get(target, exportName) {
      if (typeof exportName !== "string") return undefined;
      
      return {
        $$typeof: CLIENT_REFERENCE_SYMBOL,
        $$id: moduleId,
        $$name: exportName,
      };
    },
  });
}

export default createClientModuleProxy(${JSON.stringify(moduleId)});
`;
}
