/**
 * @file Client Reference Code Generation
 * Generate code that uses @my-react/react-server runtime APIs
 *
 * These functions generate CODE STRINGS (not runtime objects).
 * The generated code imports from @my-react/react-server/server at runtime.
 */

/**
 * Generate client reference proxy code for server-side rendering
 *
 * The generated code uses `registerClientReference` from @my-react/react-server/server
 * which properly integrates with the Flight serialization.
 *
 * @param moduleId - The module ID
 * @param exports - Named exports
 * @param hasDefaultExport - Whether there's a default export
 * @returns Generated proxy code string
 */
export function generateClientReferenceProxyCode(moduleId: string, exports: string[], hasDefaultExport: boolean): string {
  const lines: string[] = [
    "// Client reference proxy generated by @my-react/react-vite RSC",
    "// Uses runtime API from @my-react/react-server/server",
    'import { registerClientReference } from "@my-react/react-server/server";',
    "",
  ];

  // Generate exports using the runtime API
  if (hasDefaultExport) {
    lines.push(`const __default__ = registerClientReference({}, ${JSON.stringify(moduleId)}, "default");`);
    lines.push("export default __default__;");
    lines.push("");
  }

  for (const exportName of exports) {
    if (exportName === "default") continue;
    // Ensure valid JS identifier
    const safeName = exportName.replace(/[^a-zA-Z0-9_$]/g, "_");
    lines.push(`export const ${safeName} = registerClientReference({}, ${JSON.stringify(moduleId)}, ${JSON.stringify(exportName)});`);
  }

  return lines.join("\n");
}

/**
 * Generate module proxy code for all exports in a client module
 *
 * The generated code uses `createClientModuleProxy` from @my-react/react-server/server
 * which creates a Proxy that returns client references for any property access.
 *
 * @param moduleId - The module ID
 * @returns Generated proxy code string
 */
export function generateClientModuleProxyCode(moduleId: string): string {
  return `// Client module proxy generated by @my-react/react-vite RSC
// Uses runtime API from @my-react/react-server/server
import { createClientModuleProxy } from "@my-react/react-server/server";

export default createClientModuleProxy(${JSON.stringify(moduleId)});
`;
}

/**
 * @deprecated Use generateClientModuleProxyCode instead
 */
export const createClientModuleProxy = generateClientModuleProxyCode;
