/**
 * @file Server Action Code Generation
 * Generate server reference registration code
 */

import type { ServerActionRegistry } from "./server-registry";

/**
 * Generate server module code with server reference registration
 *
 * @param originalCode - The original code
 * @param moduleId - The module ID
 * @param actions - The action names
 * @returns Generated code
 */
export function generateServerModuleCode(originalCode: string, moduleId: string, actions: string[]): string {
  const lines: string[] = [
    "// Server module with registered actions - generated by @my-react/react-vite RSC",
    'const SERVER_REFERENCE_SYMBOL = Symbol.for("my-react.server.reference");',
    "",
    "function registerServerReference(fn, moduleId, name) {",
    "  fn.$$typeof = SERVER_REFERENCE_SYMBOL;",
    "  fn.$$id = `${moduleId}#${name}`;",
    "  fn.$$name = name;",
    "  fn.$$bound = undefined;",
    "  return fn;",
    "}",
    "",
  ];

  // Add the original code (stripping the "use server" directive)
  const codeWithoutDirective = originalCode.replace(/^[\s\r\n]*(['"`])use server\1[\s]*;?/, "");
  lines.push(codeWithoutDirective);
  lines.push("");

  // Generate registration calls for each action
  lines.push("// Register server references");
  for (const action of actions) {
    if (action === "default") {
      // Handle default export differently - we can't modify it in place
      continue;
    }
    lines.push(`if (typeof ${action} === "function") {`);
    lines.push(`  registerServerReference(${action}, ${JSON.stringify(moduleId)}, ${JSON.stringify(action)});`);
    lines.push("}");
  }

  return lines.join("\n");
}

/**
 * Generate inline server action wrapper code
 *
 * @param moduleId - The module ID
 * @param actionName - The action function name
 * @returns Comment marker for the action
 */
export function generateInlineActionMarker(moduleId: string, actionName: string): string {
  const actionId = `${moduleId}#${actionName}`;
  return `/* @__SERVER_ACTION__:${actionId} */`;
}

/**
 * Generate a server action handler entry point
 * This is used to create the server endpoint that handles action invocations
 *
 * @param registry - The server action registry
 * @returns Generated handler code
 */
export function generateServerActionHandler(registry: ServerActionRegistry): string {
  const actions = registry.getAll();

  const lines: string[] = [
    "// Server action handler - generated by @my-react/react-vite RSC",
    'import { handleServerAction } from "@my-react/react-server/server";',
    "",
  ];

  // Import all action modules
  const moduleImports = new Map<string, string[]>();
  for (const [, info] of actions) {
    const existing = moduleImports.get(info.moduleId) || [];
    existing.push(info.name);
    moduleImports.set(info.moduleId, existing);
  }

  let moduleIndex = 0;
  const moduleAliases = new Map<string, string>();
  for (const [moduleId] of moduleImports) {
    const alias = `__actions_${moduleIndex++}__`;
    moduleAliases.set(moduleId, alias);
    lines.push(`import * as ${alias} from ${JSON.stringify(moduleId)};`);
  }

  lines.push("");
  lines.push("// Action registry");
  lines.push("const actionRegistry = new Map();");

  for (const [actionId, info] of actions) {
    const alias = moduleAliases.get(info.moduleId);
    lines.push(`actionRegistry.set(${JSON.stringify(actionId)}, ${alias}.${info.name});`);
  }

  lines.push("");
  lines.push("export function getServerAction(actionId) {");
  lines.push("  return actionRegistry.get(actionId);");
  lines.push("}");
  lines.push("");
  lines.push("export { handleServerAction };");

  return lines.join("\n");
}
