export enum STATE_TYPE {
  __initial__ = 0,
  __create__ = 1 << 0,
  __stable__ = 1 << 1,
  __inherit__ = 1 << 2,
  __triggerConcurrent__ = 1 << 3,
  __triggerConcurrentForce__ = 1 << 4,
  __triggerSync__ = 1 << 5,
  __triggerSyncForce__ = 1 << 6,
  __unmount__ = 1 << 7,
  __hmr__ = 1 << 8,
  __retrigger__ = 1 << 9,
  __reschedule__ = 1 << 10,
  __recreate__ = 1 << 11,
}
