export enum HOOK_TYPE {
  useId = "useId",
  useRef = "useRef",
  useMemo = "useMemo",
  useState = "useState",
  useSignal = "useSignal",
  useEffect = "useEffect",
  useContext = "useContext",
  useReducer = "useReducer",
  useCallback = "useCallback",
  useTransition = "useTransition",
  useDebugValue = "useDebugValue",
  useLayoutEffect = "useLayoutEffect",
  useDeferredValue = "useDeferredValue",
  useInsertionEffect = "useInsertionEffect",
  useImperativeHandle = "useImperativeHandle",
  useSyncExternalStore = "useSyncExternalStore",
}
