export enum HOOK_TYPE {
  useId = 0,
  useRef = 1,
  useMemo = 2,
  useState = 3,
  useSignal = 4,
  useEffect = 5,
  useContext = 6,
  useReducer = 7,
  useCallback = 8,
  useTransition = 9,
  useDebugValue = 10,
  useLayoutEffect = 11,
  useDeferredValue = 12,
  useInsertionEffect = 13,
  useImperativeHandle = 14,
  useSyncExternalStore = 15,
  
  useOptimistic = 16,
}
