name: auto create a pr to main when branch create

on:
  push:
    branches-ignore:
      - "develop"
      - "test/**"

jobs:
  autopr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
